apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-2
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: apps-2/
    repoURL: https://github.com/andzej505hq/argo-test.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
